# config/transition_parameters_template.yaml

# Connection Settings
connection_type: "udp"  # Options: "udp", "serial"
connection_endpoint: "udp://:14540"  # Example for UDP
# connection_endpoint: "serial:///dev/ttyUSB0:57600"  # Example for Serial

# Telemetry Parameters
telemetry_update_interval: 1.0  # (s) Interval in seconds to update telemetry data

# Transition Parameters
initial_climb_rate: 1.0  # (m/s) Climb rate during takeoff
transition_base_altitude: 10.0  # (m) Altitude at which transition starts
transition_yaw_angle: 90.0  # (degrees) Yaw angle to turn towards during transition
throttle_ramp_time: 5.0  # (s) Time to ramp throttle to max
max_throttle: 100.0  # (percent) Maximum throttle
max_tilt_pitch: 30.0  # (degrees) Maximum pitch angle for tilt

# Telemetry Monitoring Parameters
transition_air_speed: 20.0  # (m/s) Airspeed to trigger fixed-wing mode
max_altitude: 50.0  # (m) Maximum altitude allowed
transition_timeout: 120.0  # (s) Time before aborting transition

# Fail-safe Parameters
altitude_failsafe_threshold: 8.0  # (m) Altitude below which to abort
climb_rate_failsafe_threshold: 0.3  # (m/s) Climb rate below which to abort
air_speed_failsafe_threshold: 25.0  # (m/s) Airspeed above which to abort
max_pitch_failsafe: 35.0  # (degrees) Maximum pitch before abort
max_roll_failsafe: 15.0  # (degrees) Maximum roll before abort
max_altitude_failsafe: 55.0  # (m) Maximum altitude before abort
abort_return_home_delay: 5.0  # (s) Delay before returning home after abort

# Operational Flags
enable_takeoff: true  # (bool) Enable or disable takeoff functionality
verbose_mode: true    # (bool) Enable detailed telemetry logging

# Transition Logic Type
transition_type: "tailsitter_pitch_program"  # Options: "tailsitter_pitch_program", "other_transition_type"
